/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MoosendApi) {
      root.MoosendApi = {};
    }
    root.MoosendApi.ABCampaignData = factory(root.MoosendApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ABCampaignData model module.
   * @module model/ABCampaignData
   * @version 1.0
   */

  /**
   * Constructs a new <code>ABCampaignData</code>.
   * @alias module:model/ABCampaignData
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>ABCampaignData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ABCampaignData} obj Optional instance to populate.
   * @return {module:model/ABCampaignData} The populated <code>ABCampaignData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ABCampaignType')) {
        obj['ABCampaignType'] = ApiClient.convertToType(data['ABCampaignType'], 'Number');
      }
      if (data.hasOwnProperty('ABWinnerSelectionType')) {
        obj['ABWinnerSelectionType'] = ApiClient.convertToType(data['ABWinnerSelectionType'], 'Number');
      }
      if (data.hasOwnProperty('DeliveredOnA')) {
        obj['DeliveredOnA'] = ApiClient.convertToType(data['DeliveredOnA'], 'String');
      }
      if (data.hasOwnProperty('DeliveredOnB')) {
        obj['DeliveredOnB'] = ApiClient.convertToType(data['DeliveredOnB'], 'String');
      }
      if (data.hasOwnProperty('HTMLContentB')) {
        obj['HTMLContentB'] = ApiClient.convertToType(data['HTMLContentB'], 'String');
      }
      if (data.hasOwnProperty('HoursToTest')) {
        obj['HoursToTest'] = ApiClient.convertToType(data['HoursToTest'], 'Number');
      }
      if (data.hasOwnProperty('ID')) {
        obj['ID'] = ApiClient.convertToType(data['ID'], 'Number');
      }
      if (data.hasOwnProperty('ListPercentage')) {
        obj['ListPercentage'] = ApiClient.convertToType(data['ListPercentage'], 'Number');
      }
      if (data.hasOwnProperty('PlainContentB')) {
        obj['PlainContentB'] = ApiClient.convertToType(data['PlainContentB'], 'String');
      }
      if (data.hasOwnProperty('SenderB')) {
        obj['SenderB'] = ApiClient.convertToType(data['SenderB'], 'String');
      }
      if (data.hasOwnProperty('SubjectB')) {
        obj['SubjectB'] = ApiClient.convertToType(data['SubjectB'], 'String');
      }
      if (data.hasOwnProperty('WebLocationB')) {
        obj['WebLocationB'] = ApiClient.convertToType(data['WebLocationB'], 'String');
      }
    }
    return obj;
  }

  /**
   * 
   * @member {Number} ABCampaignType
   */
  exports.prototype['ABCampaignType'] = undefined;
  /**
   * 
   * @member {Number} ABWinnerSelectionType
   */
  exports.prototype['ABWinnerSelectionType'] = undefined;
  /**
   * 
   * @member {String} DeliveredOnA
   */
  exports.prototype['DeliveredOnA'] = undefined;
  /**
   * 
   * @member {String} DeliveredOnB
   */
  exports.prototype['DeliveredOnB'] = undefined;
  /**
   * 
   * @member {String} HTMLContentB
   */
  exports.prototype['HTMLContentB'] = undefined;
  /**
   * 
   * @member {Number} HoursToTest
   */
  exports.prototype['HoursToTest'] = undefined;
  /**
   * 
   * @member {Number} ID
   */
  exports.prototype['ID'] = undefined;
  /**
   * 
   * @member {Number} ListPercentage
   */
  exports.prototype['ListPercentage'] = undefined;
  /**
   * 
   * @member {String} PlainContentB
   */
  exports.prototype['PlainContentB'] = undefined;
  /**
   * 
   * @member {String} SenderB
   */
  exports.prototype['SenderB'] = undefined;
  /**
   * 
   * @member {String} SubjectB
   */
  exports.prototype['SubjectB'] = undefined;
  /**
   * 
   * @member {String} WebLocationB
   */
  exports.prototype['WebLocationB'] = undefined;



  return exports;
}));


