/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Subscribers'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Subscribers'));
  } else {
    // Browser globals (root is window)
    if (!root.MoosendApi) {
      root.MoosendApi = {};
    }
    root.MoosendApi.AddingMultipleSubscribersRequest = factory(root.MoosendApi.ApiClient, root.MoosendApi.Subscribers);
  }
}(this, function(ApiClient, Subscribers) {
  'use strict';




  /**
   * The AddingMultipleSubscribersRequest model module.
   * @module model/AddingMultipleSubscribersRequest
   * @version 1.0
   */

  /**
   * Constructs a new <code>AddingMultipleSubscribersRequest</code>.
   * @alias module:model/AddingMultipleSubscribersRequest
   * @class
   * @param subscribers {Array.<module:model/Subscribers>} A list of subscribers to add to the mailing list. You may specify the email address, the name and the custom fields for each subscriber. The following example demonstrates the format each subscriber should be written in your request, assuming that you also have two custom fields named Age and Country.
   */
  var exports = function(subscribers) {
    var _this = this;

    _this['Subscribers'] = subscribers;
  };

  /**
   * Constructs a <code>AddingMultipleSubscribersRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddingMultipleSubscribersRequest} obj Optional instance to populate.
   * @return {module:model/AddingMultipleSubscribersRequest} The populated <code>AddingMultipleSubscribersRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Subscribers')) {
        obj['Subscribers'] = ApiClient.convertToType(data['Subscribers'], [Subscribers]);
      }
    }
    return obj;
  }

  /**
   * A list of subscribers to add to the mailing list. You may specify the email address, the name and the custom fields for each subscriber. The following example demonstrates the format each subscriber should be written in your request, assuming that you also have two custom fields named Age and Country.
   * @member {Array.<module:model/Subscribers>} Subscribers
   */
  exports.prototype['Subscribers'] = undefined;



  return exports;
}));


