/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MailingList68'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MailingList68'));
  } else {
    // Browser globals (root is window)
    if (!root.MoosendApi) {
      root.MoosendApi = {};
    }
    root.MoosendApi.Campaign = factory(root.MoosendApi.ApiClient, root.MoosendApi.MailingList68);
  }
}(this, function(ApiClient, MailingList68) {
  'use strict';




  /**
   * The Campaign model module.
   * @module model/Campaign
   * @version 1.0
   */

  /**
   * Constructs a new <code>Campaign</code>.
   * @alias module:model/Campaign
   * @class
   */
  var exports = function() {
    var _this = this;




























  };

  /**
   * Constructs a <code>Campaign</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Campaign} obj Optional instance to populate.
   * @return {module:model/Campaign} The populated <code>Campaign</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ABCampaignType')) {
        obj['ABCampaignType'] = ApiClient.convertToType(data['ABCampaignType'], 'Number');
      }
      if (data.hasOwnProperty('ABHoursToTest')) {
        obj['ABHoursToTest'] = ApiClient.convertToType(data['ABHoursToTest'], 'Number');
      }
      if (data.hasOwnProperty('ABWinner')) {
        obj['ABWinner'] = ApiClient.convertToType(data['ABWinner'], 'Number');
      }
      if (data.hasOwnProperty('ABWinnerSelectionType')) {
        obj['ABWinnerSelectionType'] = ApiClient.convertToType(data['ABWinnerSelectionType'], 'Number');
      }
      if (data.hasOwnProperty('ConfirmationTo')) {
        obj['ConfirmationTo'] = ApiClient.convertToType(data['ConfirmationTo'], 'String');
      }
      if (data.hasOwnProperty('CreatedOn')) {
        obj['CreatedOn'] = ApiClient.convertToType(data['CreatedOn'], 'String');
      }
      if (data.hasOwnProperty('DeliveredOn')) {
        obj['DeliveredOn'] = ApiClient.convertToType(data['DeliveredOn'], 'String');
      }
      if (data.hasOwnProperty('ID')) {
        obj['ID'] = ApiClient.convertToType(data['ID'], 'String');
      }
      if (data.hasOwnProperty('IsTransactional')) {
        obj['IsTransactional'] = ApiClient.convertToType(data['IsTransactional'], 'Boolean');
      }
      if (data.hasOwnProperty('MailingLists')) {
        obj['MailingLists'] = ApiClient.convertToType(data['MailingLists'], [MailingList68]);
      }
      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('RecipientsCount')) {
        obj['RecipientsCount'] = ApiClient.convertToType(data['RecipientsCount'], 'Number');
      }
      if (data.hasOwnProperty('ScheduledFor')) {
        obj['ScheduledFor'] = ApiClient.convertToType(data['ScheduledFor'], 'String');
      }
      if (data.hasOwnProperty('ScheduledForTimezone')) {
        obj['ScheduledForTimezone'] = ApiClient.convertToType(data['ScheduledForTimezone'], 'String');
      }
      if (data.hasOwnProperty('SiteName')) {
        obj['SiteName'] = ApiClient.convertToType(data['SiteName'], 'String');
      }
      if (data.hasOwnProperty('Status')) {
        obj['Status'] = ApiClient.convertToType(data['Status'], 'Number');
      }
      if (data.hasOwnProperty('Subject')) {
        obj['Subject'] = ApiClient.convertToType(data['Subject'], 'String');
      }
      if (data.hasOwnProperty('TotalBounces')) {
        obj['TotalBounces'] = ApiClient.convertToType(data['TotalBounces'], 'Number');
      }
      if (data.hasOwnProperty('TotalComplaints')) {
        obj['TotalComplaints'] = ApiClient.convertToType(data['TotalComplaints'], 'Number');
      }
      if (data.hasOwnProperty('TotalForwards')) {
        obj['TotalForwards'] = ApiClient.convertToType(data['TotalForwards'], 'Number');
      }
      if (data.hasOwnProperty('TotalLinkClicks')) {
        obj['TotalLinkClicks'] = ApiClient.convertToType(data['TotalLinkClicks'], 'Number');
      }
      if (data.hasOwnProperty('TotalOpens')) {
        obj['TotalOpens'] = ApiClient.convertToType(data['TotalOpens'], 'Number');
      }
      if (data.hasOwnProperty('TotalSent')) {
        obj['TotalSent'] = ApiClient.convertToType(data['TotalSent'], 'Number');
      }
      if (data.hasOwnProperty('TotalUnsubscribes')) {
        obj['TotalUnsubscribes'] = ApiClient.convertToType(data['TotalUnsubscribes'], 'Number');
      }
      if (data.hasOwnProperty('UniqueForwards')) {
        obj['UniqueForwards'] = ApiClient.convertToType(data['UniqueForwards'], 'Number');
      }
      if (data.hasOwnProperty('UniqueLinkClicks')) {
        obj['UniqueLinkClicks'] = ApiClient.convertToType(data['UniqueLinkClicks'], 'Number');
      }
      if (data.hasOwnProperty('UniqueOpens')) {
        obj['UniqueOpens'] = ApiClient.convertToType(data['UniqueOpens'], 'Number');
      }
    }
    return obj;
  }

  /**
   * 
   * @member {Number} ABCampaignType
   */
  exports.prototype['ABCampaignType'] = undefined;
  /**
   * 
   * @member {Number} ABHoursToTest
   */
  exports.prototype['ABHoursToTest'] = undefined;
  /**
   * 
   * @member {Number} ABWinner
   */
  exports.prototype['ABWinner'] = undefined;
  /**
   * 
   * @member {Number} ABWinnerSelectionType
   */
  exports.prototype['ABWinnerSelectionType'] = undefined;
  /**
   * 
   * @member {String} ConfirmationTo
   */
  exports.prototype['ConfirmationTo'] = undefined;
  /**
   * 
   * @member {String} CreatedOn
   */
  exports.prototype['CreatedOn'] = undefined;
  /**
   * 
   * @member {String} DeliveredOn
   */
  exports.prototype['DeliveredOn'] = undefined;
  /**
   * 
   * @member {String} ID
   */
  exports.prototype['ID'] = undefined;
  /**
   * 
   * @member {Boolean} IsTransactional
   */
  exports.prototype['IsTransactional'] = undefined;
  /**
   * 
   * @member {Array.<module:model/MailingList68>} MailingLists
   */
  exports.prototype['MailingLists'] = undefined;
  /**
   * 
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * 
   * @member {Number} RecipientsCount
   */
  exports.prototype['RecipientsCount'] = undefined;
  /**
   * 
   * @member {String} ScheduledFor
   */
  exports.prototype['ScheduledFor'] = undefined;
  /**
   * 
   * @member {String} ScheduledForTimezone
   */
  exports.prototype['ScheduledForTimezone'] = undefined;
  /**
   * 
   * @member {String} SiteName
   */
  exports.prototype['SiteName'] = undefined;
  /**
   * 
   * @member {Number} Status
   */
  exports.prototype['Status'] = undefined;
  /**
   * 
   * @member {String} Subject
   */
  exports.prototype['Subject'] = undefined;
  /**
   * 
   * @member {Number} TotalBounces
   */
  exports.prototype['TotalBounces'] = undefined;
  /**
   * 
   * @member {Number} TotalComplaints
   */
  exports.prototype['TotalComplaints'] = undefined;
  /**
   * 
   * @member {Number} TotalForwards
   */
  exports.prototype['TotalForwards'] = undefined;
  /**
   * 
   * @member {Number} TotalLinkClicks
   */
  exports.prototype['TotalLinkClicks'] = undefined;
  /**
   * 
   * @member {Number} TotalOpens
   */
  exports.prototype['TotalOpens'] = undefined;
  /**
   * 
   * @member {Number} TotalSent
   */
  exports.prototype['TotalSent'] = undefined;
  /**
   * 
   * @member {Number} TotalUnsubscribes
   */
  exports.prototype['TotalUnsubscribes'] = undefined;
  /**
   * 
   * @member {Number} UniqueForwards
   */
  exports.prototype['UniqueForwards'] = undefined;
  /**
   * 
   * @member {Number} UniqueLinkClicks
   */
  exports.prototype['UniqueLinkClicks'] = undefined;
  /**
   * 
   * @member {Number} UniqueOpens
   */
  exports.prototype['UniqueOpens'] = undefined;



  return exports;
}));


