/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MailingList85', 'model/ReplyToEmail', 'model/Sender'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MailingList85'), require('./ReplyToEmail'), require('./Sender'));
  } else {
    // Browser globals (root is window)
    if (!root.MoosendApi) {
      root.MoosendApi = {};
    }
    root.MoosendApi.Context84 = factory(root.MoosendApi.ApiClient, root.MoosendApi.MailingList85, root.MoosendApi.ReplyToEmail, root.MoosendApi.Sender);
  }
}(this, function(ApiClient, MailingList85, ReplyToEmail, Sender) {
  'use strict';




  /**
   * The Context84 model module.
   * @module model/Context84
   * @version 1.0
   */

  /**
   * Constructs a new <code>Context84</code>.
   * @alias module:model/Context84
   * @class
   */
  var exports = function() {
    var _this = this;




















  };

  /**
   * Constructs a <code>Context84</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Context84} obj Optional instance to populate.
   * @return {module:model/Context84} The populated <code>Context84</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ABCampaignData')) {
        obj['ABCampaignData'] = ApiClient.convertToType(data['ABCampaignData'], 'String');
      }
      if (data.hasOwnProperty('ConfirmationTo')) {
        obj['ConfirmationTo'] = ApiClient.convertToType(data['ConfirmationTo'], 'String');
      }
      if (data.hasOwnProperty('CreatedOn')) {
        obj['CreatedOn'] = ApiClient.convertToType(data['CreatedOn'], 'String');
      }
      if (data.hasOwnProperty('DeliveredOn')) {
        obj['DeliveredOn'] = ApiClient.convertToType(data['DeliveredOn'], 'String');
      }
      if (data.hasOwnProperty('FormatType')) {
        obj['FormatType'] = ApiClient.convertToType(data['FormatType'], 'Number');
      }
      if (data.hasOwnProperty('HTMLContent')) {
        obj['HTMLContent'] = ApiClient.convertToType(data['HTMLContent'], 'String');
      }
      if (data.hasOwnProperty('ID')) {
        obj['ID'] = ApiClient.convertToType(data['ID'], 'String');
      }
      if (data.hasOwnProperty('IsTransactional')) {
        obj['IsTransactional'] = ApiClient.convertToType(data['IsTransactional'], 'Boolean');
      }
      if (data.hasOwnProperty('MailingLists')) {
        obj['MailingLists'] = ApiClient.convertToType(data['MailingLists'], [MailingList85]);
      }
      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('PlainContent')) {
        obj['PlainContent'] = ApiClient.convertToType(data['PlainContent'], 'String');
      }
      if (data.hasOwnProperty('ReplyToEmail')) {
        obj['ReplyToEmail'] = ReplyToEmail.constructFromObject(data['ReplyToEmail']);
      }
      if (data.hasOwnProperty('ScheduledFor')) {
        obj['ScheduledFor'] = ApiClient.convertToType(data['ScheduledFor'], 'String');
      }
      if (data.hasOwnProperty('Sender')) {
        obj['Sender'] = Sender.constructFromObject(data['Sender']);
      }
      if (data.hasOwnProperty('Status')) {
        obj['Status'] = ApiClient.convertToType(data['Status'], 'Number');
      }
      if (data.hasOwnProperty('Subject')) {
        obj['Subject'] = ApiClient.convertToType(data['Subject'], 'String');
      }
      if (data.hasOwnProperty('Timezone')) {
        obj['Timezone'] = ApiClient.convertToType(data['Timezone'], 'String');
      }
      if (data.hasOwnProperty('UpdatedOn')) {
        obj['UpdatedOn'] = ApiClient.convertToType(data['UpdatedOn'], 'String');
      }
      if (data.hasOwnProperty('WebLocation')) {
        obj['WebLocation'] = ApiClient.convertToType(data['WebLocation'], 'String');
      }
    }
    return obj;
  }

  /**
   * 
   * @member {String} ABCampaignData
   */
  exports.prototype['ABCampaignData'] = undefined;
  /**
   * 
   * @member {String} ConfirmationTo
   */
  exports.prototype['ConfirmationTo'] = undefined;
  /**
   * 
   * @member {String} CreatedOn
   */
  exports.prototype['CreatedOn'] = undefined;
  /**
   * 
   * @member {String} DeliveredOn
   */
  exports.prototype['DeliveredOn'] = undefined;
  /**
   * 
   * @member {Number} FormatType
   */
  exports.prototype['FormatType'] = undefined;
  /**
   * 
   * @member {String} HTMLContent
   */
  exports.prototype['HTMLContent'] = undefined;
  /**
   * 
   * @member {String} ID
   */
  exports.prototype['ID'] = undefined;
  /**
   * 
   * @member {Boolean} IsTransactional
   */
  exports.prototype['IsTransactional'] = undefined;
  /**
   * 
   * @member {Array.<module:model/MailingList85>} MailingLists
   */
  exports.prototype['MailingLists'] = undefined;
  /**
   * 
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * 
   * @member {String} PlainContent
   */
  exports.prototype['PlainContent'] = undefined;
  /**
   * @member {module:model/ReplyToEmail} ReplyToEmail
   */
  exports.prototype['ReplyToEmail'] = undefined;
  /**
   * 
   * @member {String} ScheduledFor
   */
  exports.prototype['ScheduledFor'] = undefined;
  /**
   * @member {module:model/Sender} Sender
   */
  exports.prototype['Sender'] = undefined;
  /**
   * 
   * @member {Number} Status
   */
  exports.prototype['Status'] = undefined;
  /**
   * 
   * @member {String} Subject
   */
  exports.prototype['Subject'] = undefined;
  /**
   * 
   * @member {String} Timezone
   */
  exports.prototype['Timezone'] = undefined;
  /**
   * 
   * @member {String} UpdatedOn
   */
  exports.prototype['UpdatedOn'] = undefined;
  /**
   * 
   * @member {String} WebLocation
   */
  exports.prototype['WebLocation'] = undefined;



  return exports;
}));


