/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/A', 'model/B'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./A'), require('./B'));
  } else {
    // Browser globals (root is window)
    if (!root.MoosendApi) {
      root.MoosendApi = {};
    }
    root.MoosendApi.Context132 = factory(root.MoosendApi.ApiClient, root.MoosendApi.A, root.MoosendApi.B);
  }
}(this, function(ApiClient, A, B) {
  'use strict';




  /**
   * The Context132 model module.
   * @module model/Context132
   * @version 1.0
   */

  /**
   * Constructs a new <code>Context132</code>.
   * @alias module:model/Context132
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Context132</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Context132} obj Optional instance to populate.
   * @return {module:model/Context132} The populated <code>Context132</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('A')) {
        obj['A'] = A.constructFromObject(data['A']);
      }
      if (data.hasOwnProperty('B')) {
        obj['B'] = B.constructFromObject(data['B']);
      }
      if (data.hasOwnProperty('CampaignID')) {
        obj['CampaignID'] = ApiClient.convertToType(data['CampaignID'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/A} A
   */
  exports.prototype['A'] = undefined;
  /**
   * @member {module:model/B} B
   */
  exports.prototype['B'] = undefined;
  /**
   * 
   * @member {String} CampaignID
   */
  exports.prototype['CampaignID'] = undefined;



  return exports;
}));


