/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MoosendApi) {
      root.MoosendApi = {};
    }
    root.MoosendApi.Context64 = factory(root.MoosendApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Context64 model module.
   * @module model/Context64
   * @version 1.0
   */

  /**
   * Constructs a new <code>Context64</code>.
   * @alias module:model/Context64
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>Context64</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Context64} obj Optional instance to populate.
   * @return {module:model/Context64} The populated <code>Context64</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('EmailsIgnored')) {
        obj['EmailsIgnored'] = ApiClient.convertToType(data['EmailsIgnored'], 'Number');
      }
      if (data.hasOwnProperty('EmailsProcessed')) {
        obj['EmailsProcessed'] = ApiClient.convertToType(data['EmailsProcessed'], 'Number');
      }
    }
    return obj;
  }

  /**
   * 
   * @member {Number} EmailsIgnored
   */
  exports.prototype['EmailsIgnored'] = undefined;
  /**
   * 
   * @member {Number} EmailsProcessed
   */
  exports.prototype['EmailsProcessed'] = undefined;



  return exports;
}));


