/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MoosendApi) {
      root.MoosendApi = {};
    }
    root.MoosendApi.CreatingANewSegmentRequest = factory(root.MoosendApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CreatingANewSegmentRequest model module.
   * @module model/CreatingANewSegmentRequest
   * @version 1.0
   */

  /**
   * Constructs a new <code>CreatingANewSegmentRequest</code>.
   * @alias module:model/CreatingANewSegmentRequest
   * @class
   * @param name {String} The name of the segment.
   */
  var exports = function(name) {
    var _this = this;

    _this['Name'] = name;

  };

  /**
   * Constructs a <code>CreatingANewSegmentRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreatingANewSegmentRequest} obj Optional instance to populate.
   * @return {module:model/CreatingANewSegmentRequest} The populated <code>CreatingANewSegmentRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('MatchType')) {
        obj['MatchType'] = ApiClient.convertToType(data['MatchType'], 'String');
      }
    }
    return obj;
  }

  /**
   * The name of the segment.
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * Specifies how the segment's criteria will match together. This must be one of the following values. If not specified, `All` will be assumed.
   * @member {String} MatchType
   */
  exports.prototype['MatchType'] = undefined;



  return exports;
}));


