/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MoosendApi) {
      root.MoosendApi = {};
    }
    root.MoosendApi.MailingList85 = factory(root.MoosendApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MailingList85 model module.
   * @module model/MailingList85
   * @version 1.0
   */

  /**
   * Constructs a new <code>MailingList85</code>.
   * @alias module:model/MailingList85
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>MailingList85</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MailingList85} obj Optional instance to populate.
   * @return {module:model/MailingList85} The populated <code>MailingList85</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('MailingListID')) {
        obj['MailingListID'] = ApiClient.convertToType(data['MailingListID'], 'String');
      }
      if (data.hasOwnProperty('SegmentID')) {
        obj['SegmentID'] = ApiClient.convertToType(data['SegmentID'], 'Number');
      }
    }
    return obj;
  }

  /**
   * 
   * @member {String} MailingListID
   */
  exports.prototype['MailingListID'] = undefined;
  /**
   * 
   * @member {Number} SegmentID
   */
  exports.prototype['SegmentID'] = undefined;



  return exports;
}));


