/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MoosendApi) {
      root.MoosendApi = {};
    }
    root.MoosendApi.MailingLists = factory(root.MoosendApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MailingLists model module.
   * @module model/MailingLists
   * @version 1.0
   */

  /**
   * Constructs a new <code>MailingLists</code>.
   * @alias module:model/MailingLists
   * @class
   * @param mailingListId {String} A Mailing list id
   */
  var exports = function(mailingListId) {
    var _this = this;

    _this['MailingListId'] = mailingListId;

  };

  /**
   * Constructs a <code>MailingLists</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MailingLists} obj Optional instance to populate.
   * @return {module:model/MailingLists} The populated <code>MailingLists</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('MailingListId')) {
        obj['MailingListId'] = ApiClient.convertToType(data['MailingListId'], 'String');
      }
      if (data.hasOwnProperty('SegmentId')) {
        obj['SegmentId'] = ApiClient.convertToType(data['SegmentId'], 'Number');
      }
    }
    return obj;
  }

  /**
   * A Mailing list id
   * @member {String} MailingListId
   */
  exports.prototype['MailingListId'] = undefined;
  /**
   * Possible values : (whatever, random, fuck)
   * @member {Number} SegmentId
   */
  exports.prototype['SegmentId'] = undefined;



  return exports;
}));


