/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MoosendApi) {
      root.MoosendApi = {};
    }
    root.MoosendApi.ReplyToEmail = factory(root.MoosendApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ReplyToEmail model module.
   * @module model/ReplyToEmail
   * @version 1.0
   */

  /**
   * Constructs a new <code>ReplyToEmail</code>.
   * @alias module:model/ReplyToEmail
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>ReplyToEmail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReplyToEmail} obj Optional instance to populate.
   * @return {module:model/ReplyToEmail} The populated <code>ReplyToEmail</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('CreatedOn')) {
        obj['CreatedOn'] = ApiClient.convertToType(data['CreatedOn'], 'String');
      }
      if (data.hasOwnProperty('DkimPublic')) {
        obj['DkimPublic'] = ApiClient.convertToType(data['DkimPublic'], 'String');
      }
      if (data.hasOwnProperty('DkimVerified')) {
        obj['DkimVerified'] = ApiClient.convertToType(data['DkimVerified'], 'Boolean');
      }
      if (data.hasOwnProperty('Email')) {
        obj['Email'] = ApiClient.convertToType(data['Email'], 'String');
      }
      if (data.hasOwnProperty('ID')) {
        obj['ID'] = ApiClient.convertToType(data['ID'], 'String');
      }
      if (data.hasOwnProperty('IsEnabled')) {
        obj['IsEnabled'] = ApiClient.convertToType(data['IsEnabled'], 'Boolean');
      }
      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('SpfVerified')) {
        obj['SpfVerified'] = ApiClient.convertToType(data['SpfVerified'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * 
   * @member {String} CreatedOn
   */
  exports.prototype['CreatedOn'] = undefined;
  /**
   * 
   * @member {String} DkimPublic
   */
  exports.prototype['DkimPublic'] = undefined;
  /**
   * 
   * @member {Boolean} DkimVerified
   */
  exports.prototype['DkimVerified'] = undefined;
  /**
   * 
   * @member {String} Email
   */
  exports.prototype['Email'] = undefined;
  /**
   * 
   * @member {String} ID
   */
  exports.prototype['ID'] = undefined;
  /**
   * 
   * @member {Boolean} IsEnabled
   */
  exports.prototype['IsEnabled'] = undefined;
  /**
   * 
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * 
   * @member {Boolean} SpfVerified
   */
  exports.prototype['SpfVerified'] = undefined;



  return exports;
}));


