/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MoosendApi) {
      root.MoosendApi = {};
    }
    root.MoosendApi.Subscribers = factory(root.MoosendApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Subscribers model module.
   * @module model/Subscribers
   * @version 1.0
   */

  /**
   * Constructs a new <code>Subscribers</code>.
   * @alias module:model/Subscribers
   * @class
   * @param email {String} 
   */
  var exports = function(email) {
    var _this = this;

    _this['Email'] = email;


  };

  /**
   * Constructs a <code>Subscribers</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Subscribers} obj Optional instance to populate.
   * @return {module:model/Subscribers} The populated <code>Subscribers</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Email')) {
        obj['Email'] = ApiClient.convertToType(data['Email'], 'String');
      }
      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('CustomFields')) {
        obj['CustomFields'] = ApiClient.convertToType(data['CustomFields'], Object);
      }
    }
    return obj;
  }

  /**
   * 
   * @member {String} Email
   */
  exports.prototype['Email'] = undefined;
  /**
   * 
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * A list of name-value pairs that match the member's custom fields defined in the mailing list.  For example, if you have two custom fields named Age and Country, you should specify values for them as following example.
   * @member {Object} CustomFields
   */
  exports.prototype['CustomFields'] = undefined;



  return exports;
}));


