/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MoosendApi) {
      root.MoosendApi = {};
    }
    root.MoosendApi.UnsubscribingSubscribersFromAccountRequest = factory(root.MoosendApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UnsubscribingSubscribersFromAccountRequest model module.
   * @module model/UnsubscribingSubscribersFromAccountRequest
   * @version 1.0
   */

  /**
   * Constructs a new <code>UnsubscribingSubscribersFromAccountRequest</code>.
   * @alias module:model/UnsubscribingSubscribersFromAccountRequest
   * @class
   * @param email {String} The email address of the member.
   */
  var exports = function(email) {
    var _this = this;

    _this['Email'] = email;
  };

  /**
   * Constructs a <code>UnsubscribingSubscribersFromAccountRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UnsubscribingSubscribersFromAccountRequest} obj Optional instance to populate.
   * @return {module:model/UnsubscribingSubscribersFromAccountRequest} The populated <code>UnsubscribingSubscribersFromAccountRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Email')) {
        obj['Email'] = ApiClient.convertToType(data['Email'], 'String');
      }
    }
    return obj;
  }

  /**
   * The email address of the member.
   * @member {String} Email
   */
  exports.prototype['Email'] = undefined;



  return exports;
}));


