/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MailingLists'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MailingLists'));
  } else {
    // Browser globals (root is window)
    if (!root.MoosendApi) {
      root.MoosendApi = {};
    }
    root.MoosendApi.UpdatingADraftCampaignRequest = factory(root.MoosendApi.ApiClient, root.MoosendApi.MailingLists);
  }
}(this, function(ApiClient, MailingLists) {
  'use strict';




  /**
   * The UpdatingADraftCampaignRequest model module.
   * @module model/UpdatingADraftCampaignRequest
   * @version 1.0
   */

  /**
   * Constructs a new <code>UpdatingADraftCampaignRequest</code>.
   * @alias module:model/UpdatingADraftCampaignRequest
   * @class
   */
  var exports = function() {
    var _this = this;



















  };

  /**
   * Constructs a <code>UpdatingADraftCampaignRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdatingADraftCampaignRequest} obj Optional instance to populate.
   * @return {module:model/UpdatingADraftCampaignRequest} The populated <code>UpdatingADraftCampaignRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('Subject')) {
        obj['Subject'] = ApiClient.convertToType(data['Subject'], 'String');
      }
      if (data.hasOwnProperty('SenderEmail')) {
        obj['SenderEmail'] = ApiClient.convertToType(data['SenderEmail'], 'String');
      }
      if (data.hasOwnProperty('ReplyToEmail')) {
        obj['ReplyToEmail'] = ApiClient.convertToType(data['ReplyToEmail'], 'String');
      }
      if (data.hasOwnProperty('IsAB')) {
        obj['IsAB'] = ApiClient.convertToType(data['IsAB'], 'String');
      }
      if (data.hasOwnProperty('ConfirmationToEmail')) {
        obj['ConfirmationToEmail'] = ApiClient.convertToType(data['ConfirmationToEmail'], 'String');
      }
      if (data.hasOwnProperty('WebLocation')) {
        obj['WebLocation'] = ApiClient.convertToType(data['WebLocation'], 'String');
      }
      if (data.hasOwnProperty('MailingLists')) {
        obj['MailingLists'] = ApiClient.convertToType(data['MailingLists'], [MailingLists]);
      }
      if (data.hasOwnProperty('SegmentID')) {
        obj['SegmentID'] = ApiClient.convertToType(data['SegmentID'], 'String');
      }
      if (data.hasOwnProperty('ABCampaignType')) {
        obj['ABCampaignType'] = ApiClient.convertToType(data['ABCampaignType'], 'String');
      }
      if (data.hasOwnProperty('TrackInGoogleAnalytics')) {
        obj['TrackInGoogleAnalytics'] = ApiClient.convertToType(data['TrackInGoogleAnalytics'], 'String');
      }
      if (data.hasOwnProperty('DontTrackLinkClicks')) {
        obj['DontTrackLinkClicks'] = ApiClient.convertToType(data['DontTrackLinkClicks'], 'String');
      }
      if (data.hasOwnProperty('SubjectB')) {
        obj['SubjectB'] = ApiClient.convertToType(data['SubjectB'], 'String');
      }
      if (data.hasOwnProperty('WebLocationB')) {
        obj['WebLocationB'] = ApiClient.convertToType(data['WebLocationB'], 'String');
      }
      if (data.hasOwnProperty('SenderEmailB')) {
        obj['SenderEmailB'] = ApiClient.convertToType(data['SenderEmailB'], 'String');
      }
      if (data.hasOwnProperty('HoursToTest')) {
        obj['HoursToTest'] = ApiClient.convertToType(data['HoursToTest'], 'String');
      }
      if (data.hasOwnProperty('ListPercentage')) {
        obj['ListPercentage'] = ApiClient.convertToType(data['ListPercentage'], 'String');
      }
      if (data.hasOwnProperty('ABWinnerSelectionType')) {
        obj['ABWinnerSelectionType'] = ApiClient.convertToType(data['ABWinnerSelectionType'], 'String');
      }
    }
    return obj;
  }

  /**
   * The name of the campaign.
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * The subject line of the new campaign.
   * @member {String} Subject
   */
  exports.prototype['Subject'] = undefined;
  /**
   * The sender email of the campaign.
   * @member {String} SenderEmail
   */
  exports.prototype['SenderEmail'] = undefined;
  /**
   * The email address to which recipients replies will arrive. It must be one of your sender accounts. If not specified, the sender's email will be assumed.
   * @member {String} ReplyToEmail
   */
  exports.prototype['ReplyToEmail'] = undefined;
  /**
   * A flag that defines if a campaign is an AB campaign.
   * @member {String} IsAB
   */
  exports.prototype['IsAB'] = undefined;
  /**
   * The email address to which a confirmation message will be,  sent when the campaign has been successfully sent.
   * @member {String} ConfirmationToEmail
   */
  exports.prototype['ConfirmationToEmail'] = undefined;
  /**
   * A url to retrieve the html content for the campaign. We'll automatically move all CSS inline.
   * @member {String} WebLocation
   */
  exports.prototype['WebLocation'] = undefined;
  /**
   * A list of mailing lists in your account to which the campaign will be sent to.
   * @member {Array.<module:model/MailingLists>} MailingLists
   */
  exports.prototype['MailingLists'] = undefined;
  /**
   * The ID of a segment in the specified mailing list to filter the recipients with. If not specified, the campaign will be sent to all active subscribers of the mailing list.
   * @member {String} SegmentID
   */
  exports.prototype['SegmentID'] = undefined;
  /**
   * If you want to send an AB split campaign you should specify this parameter to one of the following values.  * `Subject` * `Sender` * `Content`
   * @member {String} ABCampaignType
   */
  exports.prototype['ABCampaignType'] = undefined;
  /**
   * Tracks traffic from your campaign to your site. Note: You need to have Google Analytics configured on your site to use this feature.
   * @member {String} TrackInGoogleAnalytics
   */
  exports.prototype['TrackInGoogleAnalytics'] = undefined;
  /**
   * Moosend wraps your own links with its own to enable link click tracking. Check this box if you don't wish to track link click traffic through Moosend.
   * @member {String} DontTrackLinkClicks
   */
  exports.prototype['DontTrackLinkClicks'] = undefined;
  /**
   * If you wish to send an AB split campaign with two different versions of the subject line , you must specify the second subject using this parameter. If specified in any other campaign type, it will be ignored.
   * @member {String} SubjectB
   */
  exports.prototype['SubjectB'] = undefined;
  /**
   * If you wish to send an AB split campaign with two different versions of the html content, you must specify where the second html content will be retrieved from using this parameter. If specified in any other campaign type, it will be ignored.
   * @member {String} WebLocationB
   */
  exports.prototype['WebLocationB'] = undefined;
  /**
   * If you wish to send an AB split campaign with two different versions of the sender , you must specify the second sender email address using this parameter. This must be one of your sender signatures defined in your account. If specified in any other campaign type, it will be ignored.
   * @member {String} SenderEmailB
   */
  exports.prototype['SenderEmailB'] = undefined;
  /**
   * If you choose to send an AB campaign type, you must set this parameter to specify how long the test will run, before determining which will be the winning version to be sent to the rest of the recipients. This should be an integer value between 1 and 24. If specified in a regular campaign, it will be ignored.
   * @member {String} HoursToTest
   */
  exports.prototype['HoursToTest'] = undefined;
  /**
   * If you choose to send an AB campaign type, you must set this parameter to specify a portion of the target recipients that will receive the test versions. For example, if you specify 10, then 10% of your recipients will receive the A version and another 10% will receive the B version. The specified value should be an integer between 5 and 40. If specified in a regular campaign, it will be ignored. (optional, string)
   * @member {String} ListPercentage
   */
  exports.prototype['ListPercentage'] = undefined;
  /**
   * If you choose to send an AB campaign type, you may set this parameter to one of the following values to specify the method to determine the winning version for the test.   If not set, OpenRate will be assumed. If specified in a regular campaign, it will be ignored. * `OpenRate` * `TotalUniqueClicks`
   * @member {String} ABWinnerSelectionType
   */
  exports.prototype['ABWinnerSelectionType'] = undefined;



  return exports;
}));


