/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MoosendApi) {
      root.MoosendApi = {};
    }
    root.MoosendApi.UpdatingSegmentCriteriaRequest = factory(root.MoosendApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UpdatingSegmentCriteriaRequest model module.
   * @module model/UpdatingSegmentCriteriaRequest
   * @version 1.0
   */

  /**
   * Constructs a new <code>UpdatingSegmentCriteriaRequest</code>.
   * @alias module:model/UpdatingSegmentCriteriaRequest
   * @class
   * @param field {String} The field of the criterion to filter the mailing list by. This must be one of the following values.
   */
  var exports = function(field) {
    var _this = this;

    _this['Field'] = field;




  };

  /**
   * Constructs a <code>UpdatingSegmentCriteriaRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdatingSegmentCriteriaRequest} obj Optional instance to populate.
   * @return {module:model/UpdatingSegmentCriteriaRequest} The populated <code>UpdatingSegmentCriteriaRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Field')) {
        obj['Field'] = ApiClient.convertToType(data['Field'], 'String');
      }
      if (data.hasOwnProperty('Comparer')) {
        obj['Comparer'] = ApiClient.convertToType(data['Comparer'], 'String');
      }
      if (data.hasOwnProperty('Value')) {
        obj['Value'] = ApiClient.convertToType(data['Value'], 'String');
      }
      if (data.hasOwnProperty('DateFrom')) {
        obj['DateFrom'] = ApiClient.convertToType(data['DateFrom'], 'String');
      }
      if (data.hasOwnProperty('DateTo')) {
        obj['DateTo'] = ApiClient.convertToType(data['DateTo'], 'String');
      }
    }
    return obj;
  }

  /**
   * The field of the criterion to filter the mailing list by. This must be one of the following values.
   * @member {String} Field
   */
  exports.prototype['Field'] = undefined;
  /**
   * An operator that defines the way to compare a criterion field with its value. This must be one of the following values. If not specified, `Is` will be assumed.
   * @member {String} Comparer
   */
  exports.prototype['Comparer'] = undefined;
  /**
   * A search term to filter the specified field by.
   * @member {String} Value
   */
  exports.prototype['Value'] = undefined;
  /**
   * Provides an additional filter option to be combined with the following fields.
   * @member {String} DateFrom
   */
  exports.prototype['DateFrom'] = undefined;
  /**
   * Provides an additional filter option to be combined with the following fields.
   * @member {String} DateTo
   */
  exports.prototype['DateTo'] = undefined;



  return exports;
}));


