/**
 * Moosend API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MoosendApi) {
      root.MoosendApi = {};
    }
    root.MoosendApi.UpdatingAMailingListRequest = factory(root.MoosendApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UpdatingAMailingListRequest model module.
   * @module model/UpdatingAMailingListRequest
   * @version 1.0
   */

  /**
   * Constructs a new <code>UpdatingAMailingListRequest</code>.
   * @alias module:model/UpdatingAMailingListRequest
   * @class
   * @param name {String} The name of the new mailing list.
   */
  var exports = function(name) {
    var _this = this;

    _this['Name'] = name;


  };

  /**
   * Constructs a <code>UpdatingAMailingListRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UpdatingAMailingListRequest} obj Optional instance to populate.
   * @return {module:model/UpdatingAMailingListRequest} The populated <code>UpdatingAMailingListRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('ConfirmationPage')) {
        obj['ConfirmationPage'] = ApiClient.convertToType(data['ConfirmationPage'], 'String');
      }
      if (data.hasOwnProperty('RedirectAfterUnsubscribePage')) {
        obj['RedirectAfterUnsubscribePage'] = ApiClient.convertToType(data['RedirectAfterUnsubscribePage'], 'String');
      }
    }
    return obj;
  }

  /**
   * The name of the new mailing list.
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * The URL of the page that will be displayed at the end of the subscription process.
   * @member {String} ConfirmationPage
   */
  exports.prototype['ConfirmationPage'] = undefined;
  /**
   * The URL of the page that users will be redirected after unsubscribing from your mailing list.
   * @member {String} RedirectAfterUnsubscribePage
   */
  exports.prototype['RedirectAfterUnsubscribePage'] = undefined;



  return exports;
}));


